"""
Digital Twin Streamlit App
Northwestern Ontario Health Simulation
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import ks_2samp

st.set_page_config(page_title="Digital Twin — NW Ontario", layout="wide", page_icon="🏥")

# ── Sidebar ──
st.sidebar.title("🏥 Digital Twin")
st.sidebar.markdown("Northwestern Ontario Health Simulation")
page = st.sidebar.radio("Navigate", [
    "📊 Overview",
    "🔬 Model Comparison",
    "📈 Time Series",
    "🗺️ Geographic",
    "⚙️ Scenario Testing",
    "🤖 Ask AI",
])

# ── Load Data ──
@st.cache_data
def load_data():
    try:
        real    = pd.read_csv('real_patients.csv')
        gc      = pd.read_csv('synthetic_gc.csv')
        ctgan   = pd.read_csv('synthetic_ctgan.csv')
        ts      = pd.read_csv('timeseries_2021_2025.csv')
        return real, gc, ctgan, ts
    except FileNotFoundError as e:
        st.error(f"Missing file: {e}. Please run generate_synthetic.py and simulation_scenario.py first.")
        st.stop()

df_real, df_gc, df_ctgan, df_ts = load_data()

def fidelity(real, syn):
    cols = real.select_dtypes(include=np.number).columns
    ks   = np.mean([1 - ks_2samp(real[c].dropna(), syn[c].dropna())[0] for c in cols])
    cr   = real[cols].corr(method='spearman')
    cs   = syn[cols].corr(method='spearman')
    corr = 1 - np.mean(np.abs(cr - cs).values)
    return round((ks + corr) / 2 * 100, 1)

# ══════════════════════════════════════════════════════════
# PAGE 1: Overview
# ══════════════════════════════════════════════════════════
if page == "📊 Overview":
    st.title("📊 Digital Twin — Northwestern Ontario")
    st.markdown("Synthetic health data generation and scenario simulation platform.")

    score_gc    = fidelity(df_real, df_gc)
    score_ctgan = fidelity(df_real, df_ctgan)

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Source Records",     f"{len(df_real):,}",  "7 municipalities")
    col2.metric("Synthetic Records",  f"{len(df_gc):,}",    "Gaussian Copula")
    col3.metric("GC Fidelity",        f"{score_gc}%",       "KS + Corr")
    col4.metric("CTGAN Fidelity",     f"{score_ctgan}%",    "KS + Corr")

    st.markdown("---")
    st.subheader("Key Health Indicators (Real Data)")

    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric("Avg Age",          f"{df_real['age'].mean():.1f}")
        st.metric("Diabetes Rate",    f"{df_real['has_diabetes'].mean()*100:.1f}%")
    with col2:
        st.metric("Avg Risk Score",   f"{df_real['risk_score'].mean():.1f}")
        st.metric("Hypertension Rate",f"{df_real['has_hypertension'].mean()*100:.1f}%")
    with col3:
        st.metric("Avg ER Visits/yr", f"{df_real['er_visits_12mo'].mean():.2f}")
        st.metric("Mood Disorder Rate",f"{df_real['has_mood_disorder'].mean()*100:.1f}%")

    st.markdown("---")
    st.subheader("What is this platform?")
    st.markdown("""
    | Layer | Description |
    |---|---|
    | **Synthetic Data** | Patient records generated by Gaussian Copula & CTGAN |
    | **Model Comparison** | Fidelity scores & correlation matrix comparison |
    | **Time Series** | Population health trends 2021–2025 |
    | **Geographic** | Health indicators by municipality |
    | **Scenario Testing** | What-if policy simulations |
    """)

# ══════════════════════════════════════════════════════════
# PAGE 2: Model Comparison
# ══════════════════════════════════════════════════════════
elif page == "🔬 Model Comparison":
    st.title("🔬 Model Comparison: Gaussian Copula vs CTGAN")

    score_gc    = fidelity(df_real, df_gc)
    score_ctgan = fidelity(df_real, df_ctgan)

    col1, col2 = st.columns(2)
    col1.metric("Gaussian Copula Fidelity", f"{score_gc}%")
    col2.metric("CTGAN Fidelity",           f"{score_ctgan}%")

    st.warning("⚠️ Higher fidelity ≠ better model. Gaussian Copula has **zero tail dependence** — it underestimates extreme health scenarios.")

    # Fidelity bar chart
    st.subheader("Fidelity Score")
    fig, ax = plt.subplots(figsize=(5, 3))
    ax.bar(['Gaussian Copula', 'CTGAN'], [score_gc, score_ctgan],
           color=['#2e5b8e', '#e07060'], width=0.4)
    ax.set_ylim(0, 100)
    ax.axhline(90, color='green', linestyle='--', label='90% threshold')
    for i, s in enumerate([score_gc, score_ctgan]):
        ax.text(i, s+1, f'{s}%', ha='center', fontweight='bold')
    ax.legend(); ax.yaxis.grid(True, alpha=0.3)
    st.pyplot(fig)

    # Correlation Matrix
    st.subheader("Correlation Matrix Comparison")
    num_cols = df_real.select_dtypes(include=np.number).columns.tolist()
    corr_r  = df_real[num_cols].corr(method='spearman')
    corr_gc = df_gc[num_cols].corr(method='spearman')

    fig, axes = plt.subplots(1, 3, figsize=(18, 6))
    kw = dict(vmin=-1, vmax=1, cmap='RdBu_r', square=True, annot=False)
    sns.heatmap(corr_r,  ax=axes[0], **kw); axes[0].set_title('Real Data', fontweight='bold')
    sns.heatmap(corr_gc, ax=axes[1], **kw); axes[1].set_title('Gaussian Copula', fontweight='bold')
    sns.heatmap(np.abs(corr_r - corr_gc), ax=axes[2],
                vmin=0, vmax=0.5, cmap='Reds', square=True)
    axes[2].set_title('Absolute Difference', fontweight='bold')
    st.pyplot(fig)

    # Distribution comparison
    st.subheader("Distribution Comparison")
    var = st.selectbox("Select variable", ['age', 'risk_score', 'chronic_condition_count', 'er_visits_12mo', 'income'])
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))
    axes[0].hist(df_real[var], bins=25, alpha=0.6, color='#333', label='Real', density=True)
    axes[0].hist(df_gc[var],   bins=25, alpha=0.6, color='#2e5b8e', label='GC', density=True)
    axes[0].set_title('Real vs Gaussian Copula', fontweight='bold'); axes[0].legend()

    axes[1].hist(df_real[var],  bins=25, alpha=0.6, color='#333', label='Real', density=True)
    axes[1].hist(df_ctgan[var], bins=25, alpha=0.6, color='#e07060', label='CTGAN', density=True)
    axes[1].set_title('Real vs CTGAN', fontweight='bold'); axes[1].legend()
    st.pyplot(fig)

    # KS Test table
    st.subheader("KS Test Results")
    ks_data = []
    for col in ['age', 'income', 'risk_score', 'chronic_condition_count', 'er_visits_12mo']:
        ks_gc,    _ = ks_2samp(df_real[col], df_gc[col])
        ks_ctgan, _ = ks_2samp(df_real[col], df_ctgan[col])
        ks_data.append({
            'Variable': col,
            'GC (KS ↓ better)': round(ks_gc, 4),
            'CTGAN (KS ↓ better)': round(ks_ctgan, 4),
            'Better Model': 'GC' if ks_gc < ks_ctgan else 'CTGAN'
        })
    st.dataframe(pd.DataFrame(ks_data), use_container_width=True)

# ══════════════════════════════════════════════════════════
# PAGE 3: Time Series
# ══════════════════════════════════════════════════════════
elif page == "📈 Time Series":
    st.title("📈 Population Health Trends 2021–2025")

    yearly = df_ts.groupby('year').agg(
        avg_age=('age','mean'),
        diabetes_rate=('has_diabetes','mean'),
        hypertension_rate=('has_hypertension','mean'),
        mood_disorder_rate=('has_mood_disorder','mean'),
        avg_er=('er_visits_12mo','mean'),
        avg_risk=('risk_score','mean'),
    ).reset_index()

    metric = st.selectbox("Select metric", [
        'avg_age', 'diabetes_rate', 'hypertension_rate',
        'mood_disorder_rate', 'avg_er', 'avg_risk'
    ])

    fig, ax = plt.subplots(figsize=(9, 4))
    ax.plot(yearly['year'], yearly[metric], 'o-', color='#2e5b8e',
            linewidth=2.5, markersize=9)
    ax.fill_between(yearly['year'], yearly[metric],
                    alpha=0.15, color='#2e5b8e')
    ax.set_xlabel('Year'); ax.set_ylabel(metric)
    ax.set_title(f'{metric} over time', fontweight='bold')
    ax.set_xticks(yearly['year']); ax.yaxis.grid(True, alpha=0.3)
    st.pyplot(fig)

    st.subheader("All Metrics Table")
    st.dataframe(yearly.round(4), use_container_width=True)

# ══════════════════════════════════════════════════════════
# PAGE 4: Geographic
# ══════════════════════════════════════════════════════════
elif page == "🗺️ Geographic":
    st.title("🗺️ Geographic Distribution by Municipality")

    year_sel = st.selectbox("Select year", sorted(df_ts['year'].unique()))
    df_year  = df_ts[df_ts['year'] == year_sel]

    geo = df_year.groupby('municipality').agg(
        avg_risk=('risk_score','mean'),
        diabetes_rate=('has_diabetes','mean'),
        hypertension_rate=('has_hypertension','mean'),
        avg_er=('er_visits_12mo','mean'),
        avg_age=('age','mean'),
    ).reset_index().sort_values('avg_risk', ascending=True)

    metric_geo = st.selectbox("Select metric", ['avg_risk','diabetes_rate','hypertension_rate','avg_er','avg_age'])

    fig, ax = plt.subplots(figsize=(9, 5))
    ax.barh(geo['municipality'], geo[metric_geo], color='#2e5b8e', height=0.6)
    ax.set_title(f'{metric_geo} by Municipality ({year_sel})', fontweight='bold')
    ax.xaxis.grid(True, alpha=0.3); ax.set_axisbelow(True)
    st.pyplot(fig)

    st.dataframe(geo.round(4), use_container_width=True)

# ══════════════════════════════════════════════════════════
# PAGE 5: Scenario Testing
# ══════════════════════════════════════════════════════════
elif page == "⚙️ Scenario Testing":
    st.title("⚙️ Scenario Testing — What-If Analysis")
    st.markdown("Adjust policy levers and see the projected impact on population health.")

    col1, col2 = st.columns(2)
    with col1:
        icu_beds       = st.slider("🏥 ICU Bed Increase (%)",        0, 50, 0)
        diabetes_prog  = st.slider("💉 Diabetes Prevention (%)",     0, 50, 0)
    with col2:
        income_support = st.slider("💰 Income Support (%)",          0, 30, 0)
        mobility_prog  = st.slider("🦽 Mobility Support Program (%)",0, 50, 0)

    # Apply scenario
    df_scenario = df_real.copy()
    if icu_beds > 0:
        df_scenario['er_visits_12mo'] *= (1 - icu_beds/100 * 0.3)
    if diabetes_prog > 0:
        mask = df_scenario['has_diabetes'] == 1
        flip = np.random.rand(mask.sum()) < diabetes_prog/100
        df_scenario.loc[mask, 'has_diabetes'] = np.maximum(0,
            df_scenario.loc[mask, 'has_diabetes'] - flip.astype(int))
    if income_support > 0:
        df_scenario['income'] *= (1 + income_support/100)
        df_scenario['risk_score'] *= (1 - income_support/100 * 0.3)
    if mobility_prog > 0:
        mask = df_scenario['has_mobility_limitation'] == 1
        flip = np.random.rand(mask.sum()) < mobility_prog/100
        df_scenario.loc[mask, 'has_mobility_limitation'] = np.maximum(0,
            df_scenario.loc[mask, 'has_mobility_limitation'] - flip.astype(int))

    df_scenario['chronic_condition_count'] = (
        df_scenario['has_diabetes'] + df_scenario['has_hypertension'] +
        df_scenario['has_copd'] + df_scenario['has_heart_disease'] +
        df_scenario['has_mood_disorder'] + df_scenario['has_arthritis'] +
        df_scenario['has_dementia']
    )

    st.subheader("Impact Summary")
    col1, col2, col3, col4 = st.columns(4)
    er_delta   = df_scenario['er_visits_12mo'].mean() - df_real['er_visits_12mo'].mean()
    diab_delta = df_scenario['has_diabetes'].mean()   - df_real['has_diabetes'].mean()
    risk_delta = df_scenario['risk_score'].mean()     - df_real['risk_score'].mean()
    mob_delta  = df_scenario['has_mobility_limitation'].mean() - df_real['has_mobility_limitation'].mean()

    col1.metric("ER Visits/yr",    f"{df_scenario['er_visits_12mo'].mean():.3f}", f"{er_delta:+.3f}")
    col2.metric("Diabetes Rate",   f"{df_scenario['has_diabetes'].mean()*100:.1f}%", f"{diab_delta*100:+.1f}%")
    col3.metric("Avg Risk Score",  f"{df_scenario['risk_score'].mean():.1f}", f"{risk_delta:+.1f}")
    col4.metric("Mobility Issues", f"{df_scenario['has_mobility_limitation'].mean()*100:.1f}%", f"{mob_delta*100:+.1f}%")

    # Comparison chart
    st.subheader("Before vs After")
    metrics_compare = {
        'ER Visits': [df_real['er_visits_12mo'].mean(), df_scenario['er_visits_12mo'].mean()],
        'Diabetes Rate': [df_real['has_diabetes'].mean(), df_scenario['has_diabetes'].mean()],
        'Risk Score': [df_real['risk_score'].mean()/100, df_scenario['risk_score'].mean()/100],
        'Mobility Issues': [df_real['has_mobility_limitation'].mean(), df_scenario['has_mobility_limitation'].mean()],
    }
    fig, axes = plt.subplots(1, 4, figsize=(16, 4))
    for ax, (label, vals) in zip(axes, metrics_compare.items()):
        ax.bar(['Baseline', 'Scenario'], vals, color=['#888', '#2e5b8e'], width=0.5)
        ax.set_title(label, fontweight='bold')
        ax.yaxis.grid(True, alpha=0.3)
        for i, v in enumerate(vals):
            ax.text(i, v + max(vals)*0.01, f'{v:.3f}', ha='center', fontsize=9)
    plt.suptitle('Baseline vs Scenario Impact', fontsize=13, fontweight='bold')
    plt.tight_layout()
    st.pyplot(fig)

# ══════════════════════════════════════════════════════════
# PAGE 6: AI Q&A — Connected to Digital Twin
# ══════════════════════════════════════════════════════════
elif page == "🤖 Ask AI":
    st.title("🤖 Ask the Digital Twin")
    st.markdown("AI connected to all your real data — Overview, Time Series, Geographic & Scenarios.")

    import anthropic
    import os

    api_key = st.text_input("Enter Claude API Key", type="password",
                            value=os.environ.get("ANTHROPIC_API_KEY", ""))

    if api_key:
        # ── Build full Digital Twin context ──
        # Geographic breakdown
        geo_stats = df_ts.groupby('municipality').agg(
            avg_risk=('risk_score','mean'),
            diabetes_rate=('has_diabetes','mean'),
            hypertension_rate=('has_hypertension','mean'),
            avg_er=('er_visits_12mo','mean'),
            avg_age=('age','mean'),
            population=('age','count'),
        ).round(3).to_string()

        # Time series trends
        yearly = df_ts.groupby('year').agg(
            avg_age=('age','mean'),
            diabetes_rate=('has_diabetes','mean'),
            hypertension_rate=('has_hypertension','mean'),
            avg_er=('er_visits_12mo','mean'),
            avg_risk=('risk_score','mean'),
        ).round(3).to_string()

        # Model fidelity
        score_gc    = fidelity(df_real, df_gc)
        score_ctgan = fidelity(df_real, df_ctgan)

        # Correlation between key variables
        corr = df_real[['age','income','has_diabetes','has_hypertension',
                         'er_visits_12mo','risk_score','chronic_condition_count']].corr().round(3).to_string()

        data_summary = f"""
You are an AI analyst for the Northwestern Ontario Digital Twin health simulation platform.
You have FULL access to all real patient data. Answer questions with specific numbers from the data.

=== OVERVIEW ===
Total patient records: {len(df_real):,}
Average age: {df_real['age'].mean():.1f}
Average income: ${df_real['income'].mean():,.0f}
Diabetes rate: {df_real['has_diabetes'].mean()*100:.1f}%
Hypertension rate: {df_real['has_hypertension'].mean()*100:.1f}%
COPD rate: {df_real['has_copd'].mean()*100:.1f}%
Heart disease rate: {df_real['has_heart_disease'].mean()*100:.1f}%
Mood disorder rate: {df_real['has_mood_disorder'].mean()*100:.1f}%
Avg ER visits/year: {df_real['er_visits_12mo'].mean():.2f}
Avg risk score: {df_real['risk_score'].mean():.3f}
Avg chronic conditions: {df_real['chronic_condition_count'].mean():.2f}
Fall risk score avg: {df_real['fall_risk_score'].mean():.3f}

=== GEOGRAPHIC DATA BY MUNICIPALITY ===
{geo_stats}

=== TIME SERIES TRENDS (2021-2025) ===
{yearly}

=== SYNTHETIC DATA MODELS ===
Gaussian Copula fidelity: {score_gc}%
CTGAN fidelity: {score_ctgan}%
Data sources: Statistics Canada 2021 Census, PHAC CCDI 2018, Ontario Data Catalogue API

=== CORRELATION MATRIX ===
{corr}

Answer all questions using the data above. Be concise and cite specific numbers.
If asked about scenarios (e.g. "what if we add more ICU beds"), use the Scenario Testing logic:
- ICU beds increase → ER visits decrease proportionally
- Diabetes prevention → reduces diabetes rate
- Income support → reduces risk scores
        """

        if "messages" not in st.session_state:
            st.session_state.messages = []

        # Show chat history
        for msg in st.session_state.messages:
            with st.chat_message(msg["role"]):
                st.write(msg["content"])

        # Suggested questions
        if not st.session_state.messages:
            st.markdown("**Try asking:**")
            cols = st.columns(3)
            suggestions = [
                "Which municipality has the highest diabetes rate?",
                "How has ER visits changed from 2021 to 2025?",
                "What happens if we increase ICU beds by 20%?",
                "Which age group has the highest risk score?",
                "How does income correlate with health outcomes?",
                "Compare Gaussian Copula vs CTGAN fidelity",
            ]
            for i, s in enumerate(suggestions):
                if cols[i % 3].button(s, key=f"sug_{i}"):
                    st.session_state.messages.append({"role": "user", "content": s})
                    st.rerun()

        # Chat input
        if question := st.chat_input("Ask anything about the Digital Twin data..."):
            st.session_state.messages.append({"role": "user", "content": question})
            with st.chat_message("user"):
                st.write(question)

            with st.chat_message("assistant"):
                with st.spinner("Querying Digital Twin..."):
                    try:
                        client = anthropic.Anthropic(api_key=api_key)
                        response = client.messages.create(
                            model="claude-opus-4-6",
                            max_tokens=1024,
                            system=data_summary,
                            messages=[
                                {"role": m["role"], "content": m["content"]}
                                for m in st.session_state.messages
                            ]
                        )
                        answer = response.content[0].text
                        st.write(answer)
                        st.session_state.messages.append(
                            {"role": "assistant", "content": answer}
                        )
                    except Exception as e:
                        st.error(f"Error: {e}")

        # Clear chat button
        if st.session_state.messages:
            if st.button("🗑️ Clear Chat"):
                st.session_state.messages = []
                st.rerun()
    else:
        st.info("👆 Enter your Claude API Key to start asking questions")
